media: media
content:
  - name: posts
    label: Posts
    type: collection
    path: src/content/posts
    view: 
      fields: ["title","categories","author","body","slug","description","draft","pin", "pubDate","modDate"]
    fields:
      - name: title
        label: Title
        type: string
      - name: categories
        label: Categories
        type: select
        options:
          values: [ Poesía, Cerebro, Manifiesto, Genodemia, Botaje ]
          multiple: true
          creatable: true
      - name: author
        label: Author
        type: string
      - name: slug
        label: Slug
        type: string
      - name: body
        label: Body
        type: rich-text
      - name: description
        label: Description
        type: string
      - name: draft
        label: Draft
        type: boolean
      - name: pin
        label: Pin
        type: boolean
      - name: pubDate
        label: Publish Date
        type: date
        options:
          format: yyyy-dd-MM
          min: 2025-27-04-
  - name: authors
    label: Authors
    type: collection
    path: src/content/signatures
    view: 
      fields: ["name","review"]
    fields: 
      - name: name
        label: name
        type: string
      - name: review
        label: description
        type: string